### ISSUE TITLE
LOOOOL 

### ISSUE THREAD

**Issue by gogosimba** [Gothfinger/HTS_Programming#2]
Jo jag försökte ju den sajten för många år sen, med mitt gamla nickname, men var svårt...

**Comment by Gothfinger** [comment]
lol jojo men "I'm doing my part". 

Skaffa simpleX chat, här är en invite:
https://simplex.chat/invitation#/?v=2-7&smp=smp%3A%2F%2Fh--vW7ZSkXPeOUpfxlFGgauQmXNFOzGoizak7Ult7cw%3D%40smp15.simplex.im%2FOmGJqYOGFu8TgFZQIDCVWmfZckV-_khI%23%2F%3Fv%3D1-3%26dh%3DMCowBQYDK2VuAyEAj0-BIeNMM0VHOmx7iqlIIk1U9vMqag9dWF3galTWbww%253D%26k%3Ds%26srv%3Doauu4bgijybyhczbnxtlggo6hiubahmeutaqineuyy23aojpih3dajad.onion&e2e=v%3D2-3%26x3dh%3DMEIwBQYDK2VvAzkAT4yK2xbLMGxV39sCuyqv94sNwpQttfXPWeZiJnZHvM8GfJmXoEYS_Xr9aD3Iea8fMSKJUNGaD0Q%3D%2CMEIwBQYDK2VvAzkAEkdioSutEMLfP90wSIKbLGU7_HeKkNXYU-dvsP_SaMCiDsGPzt7Te8dMZf_SQAFaAdGVNtlNOKk%3D

**Comment by Gothfinger** [comment]
Aa såg det hehe, kolla ditt gamla konto _thenicelordj_ på hackthissite så har du en kommentar från mig hehe ;)
